# Generated by Django 5.1.7 on 2025-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('commend', models.CharField(max_length=100)),
                ('postData', models.ImageField(blank=True, null=True, upload_to='post/images0')),
            ],
        ),
    ]
