# Generated by Django 5.1.7 on 2025-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postData',
            field=models.ImageField(blank=True, null=True, upload_to='post/images'),
        ),
    ]
