# Generated by Django 5.1.7 on 2025-04-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_post_postdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commend',
            new_name='comment',
        ),
    ]
